services:
  - type: web
    name: victory-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: COINBASE_API_KEY
        sync: false
      - key: COINBASE_API_SECRET
        sync: false
      - key: COINBASE_API_PASSPHRASE
        sync: false
